repos:
  # Python formatting with Ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.0
    hooks:
      - id: ruff-check
        args: [ --fix ]
      - id: ruff-format
  
  # Django template formatting
  # - repo: https://github.com/Riverside-Healthcare/djLint
  #   rev: v1.35.2
  #   hooks:
  #     - id: djlint-reformat-django
  #     - id: djlint-django
  
  # # CSS and JavaScript formatting
  # - repo: https://github.com/pre-commit/mirrors-prettier
  #   rev: v3.1.0
  #   hooks:
  #     - id: prettier
  #       types_or: [css, scss, javascript, json]
