# Generated by Django 5.1.5 on 2025-02-06 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='cat.png', upload_to='profile_pics'),
        ),
    ]
