# Generated by Django 5.1.5 on 2025-02-09 19:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardactivity',
            options={'verbose_name': 'Card activity', 'verbose_name_plural': 'Card activities'},
        ),
        migrations.AlterUniqueTogether(
            name='boardmember',
            unique_together={('user', 'board')},
        ),
    ]
