# Generated by Django 5.1.5 on 2025-02-14 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_list_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='list_name',
            field=models.CharField(max_length=255),
        ),
    ]
