# Generated by Django 5.1.5 on 2025-02-25 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_boardinvitaton'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardinvitaton',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired')], default='pending', max_length=12),
        ),
    ]
