# Generated by Django 5.1.5 on 2025-02-27 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_alter_boardinvitaton_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardinvitaton',
            name='status',
            field=models.CharField(choices=[('expired', 'Expired'), ('accepted', 'Accepted'), ('pending', 'Pending')], default='pending', max_length=12),
        ),
        migrations.AlterField(
            model_name='boardmember',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memofboard', to='board.board'),
        ),
        migrations.AlterField(
            model_name='boardmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boarduser', to=settings.AUTH_USER_MODEL),
        ),
    ]
