# Generated by Django 5.1.5 on 2025-10-11 20:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("board", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boardinvitaton",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("expired", "Expired"),
                ],
                default="pending",
                max_length=12,
            ),
        ),
    ]
