# Generated by Django 5.2.7 on 2025-11-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_boardinvitaton_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardinvitaton',
            name='status',
            field=models.CharField(choices=[('expired', 'Expired'), ('pending', 'Pending'), ('accepted', 'Accepted')], default='pending', max_length=12),
        ),
    ]
