# Generated by Django 6.1 on 2026-08-24 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_alter_boardinvitaton_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['position', 'id']},
        ),
        migrations.AddField(
            model_name='card',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
