# Generated by Django 6.1 on 2026-08-24 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_alter_card_options_card_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardinvitaton',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired')], default='pending', max_length=12),
        ),
    ]
