# Generated by Django 6.1 on 2026-08-24 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_card_assignee_card_cover_color_card_is_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
